services:
  mcp:
    build:
      context: ../Dockerfile/dev
      dockerfile: Dockerfile
    image: mcp
    container_name: mcp
    volumes:
      - ../src:/workspace/src
    working_dir: /workspace
    tty: true
    entrypoint: sh -c "cd src && mcp dev mcp_server.py"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "6274:6274"
      - "6277:6277"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # ":ro" は read-only の意味で、コンテナから設定ファイルを変更できなくする
    depends_on:
      - mcp
