services:
  mcp:
    build:
      context: ../Dockerfile
      dockerfile: Dockerfile
    image: mcp
    container_name: mcp
    volumes:
      - ../src:/workspace/src
    working_dir: /workspace
    tty: true

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "6274:6274"
      - "6277:6277"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - mcp
